### ISSUE TITLE
Compound of Compounds

### ISSUE THREAD

**Issue by mottosso** [mottosso/cmdx#5]
For some reason, compound children of a compound locks up Maya, presumably there's an infinite loop somewhere.

```py
import cmdx

node = cmdx.createNode("transform")

# This works
node.addAttr(
    cmdx.Compound("parent", children=[
        cmdx.Double("age"),
        cmdx.Double("height")
    ])
)

# This does *not*
node.addAttr(
    cmdx.Compound("parent", children=[
        cmdx.Compound("child", children=[
            cmdx.Double("age"),
            cmdx.Double("height")
        ])
    ])
)
```

**Comment by benoit-fouletier** [comment]
I was just about to open an issue about this, this indeed hangs hard. Any luck finding a workaround?

**Comment by mottosso** [comment]
No, sorry. I've avoided it ever since :( If you happen to come across one, please do share!

**Comment by benblo** [comment]
OK, found the issue (and a fix)!

The issue is, in `Compound.create()` (and actually in every attribute type), you use the same global (static) function set for every instance. I suspect this is a problem, since the `Fn` must actually be associated with the actual `MObject` upon `create()` . So when later you do:
```
	self.Fn.addChild(child.create(cls))
```
the child can be added to the correct `mobj`... which means you can't reuse `Fn`, it has to be unique. The same might be true (?) for the other attribute types.

I saw examples online that make this clearer:
```
	fn = om.MFnDependencyNode()
	fn.setObject(mobj)
```
... I have to admit I don't understand the API's terminology there, if the function set is indeed associated with an object then it's not really a function set but an instance isn't it, so what's the difference? beats me.

Also, I noticed that you're using `self.Fn`, but `Fn` is actually declared as a class attribute, not an instance attribute, so shouldn't it be `Compound.Fn` instead? I don't mean to be pedantic, this usage might be pythonic, but I'm quite new to Python (and Maya too actually) so still getting used to some things that feel odd to me coming from C#/C++ :relaxed:.

---

Anyway, not sure I have the correct diagnosis, but to fix this I instantiated a new `Fn` for each instance:
<pre>
    def __init__(self, name, children=None, **kwargs):
<b>        self.Fn = om.MFnCompoundAttribute()</b>
        ...
</pre>
... no more hangs!
(I don't have time atm to make a proper fork and PR, but once I do (hopefully) I'll have a few other fixes to send your way.)

---

... that being said, unfortunately the attribute editor doesn't show nested compounds :( !
Here's a simple test:
```
	compound = cmdx.Compound("cmdx_1_compound", children=[
		cmdx.String("cmdx_1_1_string", default="1_1"),
		cmdx.String("cmdx_1_2_string", default="1_2"),
		cmdx.Compound("cmdx_2_compound", children=[
			cmdx.String("cmdx_2_1_string", default="2_1"),
			cmdx.String("cmdx_2_2_string", default="2_2"),
		]),
		cmdx.String("cmdx_1_3_string", default="1_3"),
	])

	sphere = cmdx.encode(cmds.sphere()[0])
	sphere.add_attr(compound)
```
![image](https://user-images.githubusercontent.com/574187/97315595-29643d80-1869-11eb-8e22-7aac3044fea4.png)
The "cmdx_2_compound" attribute is there, but folded (children are invisible). I can query back the attributes so they're stored properly, just not displayed in the editor.

Any idea how to fix this?
I tried doing the same with cmds, or 'vanilla' OpenMaya; same result. I don't know if there's some flag I can set to tell Maya "yes please display this nested attribute", or "display up to N levels of nesting"...

---

(BTW I'm the same benoit-fouletier as earlier! I used my work account the last time, but github doesn't play nicely with multi-accounts so I'll be using my regular account from now on.)

**Comment by mottosso** [comment]
> OK, found the issue (and a fix)!

Aaaaah, yes I think you are on to something here!

> Anyway, not sure I have the correct diagnosis, but to fix this I instantiated a new Fn for each instance:

Yes, even if this isn't the solution to this particular issue, this is the correct way of doing it regardless. Let's definitely PR this.

> Also, I noticed that you're using self.Fn, but Fn is actually declared as a class attribute, not an instance attribute, so shouldn't it be Compound.Fn instead?

These are the same. I would generally use `self` to avoid having to remember or pay attention to that `Compound` is the class you're in as you read it, and not referencing some other class somewhere else in the file. But, I can see how it isn't clear-cut, as that is also the syntax of instance variables. So, I would leave it.

> unfortunately the attribute editor doesn't show nested compounds :( !

Oh that's a bummer.. My guess is you need a dedicated attribute editor template for things like that.
