### ISSUE TITLE
Thoughts on code formatter such as Black?

### ISSUE THREAD

**Issue by monkeez** [mottosso/cmdx#64]
I've found the code formatter Black to be useful on my own projects. Might be worthwhile on a large file like `cmdx.py` to keep the code style consistent?

**Comment by mottosso** [comment]
It's currently formatted (or linted, rather) using pylint and pyflake.

What inconsistency have you found? :)

**Comment by monkeez** [comment]
I did a test running it through Black:

https://github.com/monkeez/cmdx/commit/a5238bae6e2c70e101944b82c671d03ab69f7917

Some things it picked up where single quotes for strings in the `protected` decorator, condensing some function calls to single lines, single indents for nested arguments.

A lot of things are personal preference really, just thought I'd raise it as an option :)

**Comment by mottosso** [comment]
Commented on a few things in your commit. The main challenge I see is keeping both linters *and* Black happy. The secondary challenge is that clearly Black cannot make decisions about some of the things I commented about, like readability and newlines. So we would need to add exclusions either globally or line-by-line.

I'd say "pass".

Black is better suited with more chefs in the kitchen, or when the head-chef cannot keep consistent. I'd argue neither of those is the case here? I take readability and code communication very seriously. So instead of a one-size-fits-all solution like Black, my bet is on submitting an issue or PR with a specific section of code that does not read well, and address is head-on.

Those single-quote for example is a good example of an improvement, a PR would be lovely.

**Comment by monkeez** [comment]
Yeah, the only way to ignore sections in the formatter is to add comments, then you're ending up with a whole new mess.

`cmdx` has been very easy for me to read on the whole, the only formatting that kind of bothers me is the big levels on indentation in the Plug class:

![image](https://user-images.githubusercontent.com/5214414/123222287-219d8b80-d513-11eb-9ce2-91a59efa8478.png)

Though I don't know of a better way to format it.

**Comment by mottosso** [comment]
Mm, agreed. Also cannot think of an improvement.
